### ISSUE TITLE
Overlap with filesystem

### ISSUE THREAD

**Issue by clragon** [GitSquared/horizon-edex-theme#1]
Very cool theme.

The filesystem overlaps with modules further up.

![16640362](https://user-images.githubusercontent.com/11785085/68547854-f2421580-03e6-11ea-88b0-c9ed0aaa3946.png)

**Comment by GitSquared** [comment]
Screen res please?

**Comment by clragon** [comment]
1920x1080

**Comment by kalucky0** [comment]
Same issue on 2560x1080 and 1366x768

**Comment by PRODUKT-OS** [comment]
Same issue here

**Comment by outpoints** [comment]
Did you ever fix this? @GitSquared

**Comment by GitSquared** [comment]
@outpoints sorry, I haven't, I don't use this theme anymore... PRs open.

**Comment by basicx-StrgV** [comment]
I created a PR for a fix that works for 1920x1080 and lower, but I could not test it for higher resolutions.
